[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=5MB
logfile_backups=0
loglevel=info
pidfile=/tmp/supervisord.pid
childlogdir=/tmp
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf

[program:dbus-session]
command=bash -c "dbus-daemon --session --nofork --nopidfile --address=\\"$DBUS_SESSION_BUS_ADDRESS\\""
stdout_logfile=/tmp/dbus-session.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=10

[program:pipewire]
command=bash -c "until [ -S \\"$XDG_RUNTIME_DIR/bus\\" ]; do sleep 0.5; done; /usr/bin/pipewire"
stdout_logfile=/tmp/pipewire.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=20

[program:wireplumber]
command=bash -c "until [ -S \\"$XDG_RUNTIME_DIR/pipewire-0\\" ]; do sleep 0.5; done; /usr/bin/wireplumber"
stdout_logfile=/tmp/wireplumber.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=30

[program:gamescope]
command=bash -c "until pw-cli info >/dev/null 2>&1; do sleep 0.5; done; gamescope -w ${DISPLAY_SIZEW:-1920} -h ${DISPLAY_SIZEH:-1080} -W ${DISPLAY_SIZEW:-1920} -H ${DISPLAY_SIZEH:-1080} -r ${BDWIND_FRAMERATE:-60} -F fsr --backend headless -- hyprland"
stdout_logfile=/tmp/gamescope.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=40

[program:bdwind-gstreamer]
command=bash -c "/etc/beagle-wind-vnc/bdwind-gstreamer.sh"
stdout_logfile=/tmp/bdwind-gstreamer-entrypoint.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=50

[program:bdwind-gamepad]
command=/etc/beagle-wind-vnc/bdwind-gamepad.sh
stdout_logfile=/tmp/bdwind-gamepad.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=60

[program:nginx]
command=bash -c "until nc -z localhost ${BDWIND_PORT:-8081}; do sleep 0.5; done; /usr/sbin/nginx -g \\"daemon off;\\""
stdout_logfile=/tmp/nginx.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=70
