[program:bdwind-gamepad]
command=/etc/beagle-wind-vnc/bdwind-gamepad.sh
stdout_logfile=/tmp/bdwind-gamepad.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true

[program:steam-game]
command=/etc/beagle-wind-vnc/steam-game.sh
environment=DISPLAY="%(ENV_DISPLAY)s",HOME="%(ENV_HOME)s",USER="%(ENV_USER)s",DBUS_SESSION_BUS_ADDRESS="%(ENV_DBUS_SESSION_BUS_ADDRESS)s",DBUS_SYSTEM_BUS_ADDRESS="%(ENV_DBUS_SYSTEM_BUS_ADDRESS)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
stdout_logfile=/tmp/steam-game.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=false
priority=999

[program:bgctl]
command=/etc/beagle-wind-vnc/bgctl.sh
environment=DISPLAY="%(ENV_DISPLAY)s",HOME="%(ENV_HOME)s",USER="%(ENV_USER)s"
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=false
exitcodes=0
