[program:bdwind-gamepad]
command=/etc/beagle-wind-vnc/bdwind-gamepad.sh
stdout_logfile=/tmp/bdwind-gamepad.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true

