name: Build KDE6 Wayland Image

on:
  push:
    branches:
      - kde6-wayland

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push Docker image - kde6-wayland
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.beagle/kde6-wayland.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:1.2.0
            ghcr.io/${{ github.repository }}:latest-kde6-wayland
            registry.cn-qingdao.aliyuncs.com/wod/beagle-wind-vnc:1.2.0
            registry.cn-qingdao.aliyuncs.com/wod/beagle-wind-vnc:latest-kde6-wayland
          platforms: linux/amd64
          build-args: |
            BASE=ubuntu:26.04
            GSTREAMER_VERSION=1.28.4
            GSTREAMER_OS_SUFFIX=ubuntu2604
            GSTREAMER_TARBALL_URL=https://cache.ali.wodcloud.com/vscode/bdwind/bdwind-gstreamer-1.28.4-ubuntu2604.tar.gz
          no-cache: true

      - name: Image push success
        run: echo "Docker image pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/beagle-wind-vnc:1.2.0"
