name: Build Nvidia EGL Base Image

on:
  push:
    branches:
      - nvidia-egl

jobs:
  build-nvidia-egl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"

      - name: Build joystick-server
        run: bash .beagle/build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - nvidia-egl
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./nvidia/egl/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:nvidia-egl-2204-20250127
            ghcr.io/${{ github.repository }}:nvidia-egl-latest
          platforms: linux/amd64

      - name: Image push success - nvidia-egl
        run: echo "Docker image pushed successfully to ghcr.io/${{ github.repository }}:nvidia-egl-2204-20250127"
