name: Build Nvidia EGL Steam Image

on:
  push:
    branches:
      - nvidia-egl-steam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"

      - name: Build joystick-server
        run: bash .beagle/build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.beagle/nvidia-egl-steam.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:nvidia-egl-steam-1.0.0.82
            ghcr.io/${{ github.repository }}:nvidia-egl-steam-latest
            registry.cn-qingdao.aliyuncs.com/wod/beagle-wind-vnc:nvidia-egl-steam-1.0.0.82
            registry.cn-qingdao.aliyuncs.com/wod/beagle-wind-vnc:nvidia-egl-steam-latest
          platforms: linux/amd64

      - name: Image push success
        run: echo "Docker image pushed successfully to ghcr.io/${{ github.repository }}:nvidia-egl-steam-1.0.0.82"
