name: Build Wayland Hyprland Base Image

on:
  push:
    branches:
      - wayland-hyprland-base

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - wayland-hyprland-base
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.beagle/wayland-hyprland-base.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:1.1.0-base
            ghcr.io/${{ github.repository }}:latest-wayland-base
          platforms: linux/amd64
          build-args: |
            BASE=archlinux:latest
          no-cache: true

      - name: Print success message
        run: echo "Docker image pushed successfully to ghcr.io/${{ github.repository }}:1.1.0-base"
