name: Build and Push Docker Image

on:
  push:
    branches:
      - nvidia-egl-steam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./nvidia/egl/Dockerfile # Dockerfile 路径，根据您的实际情况修改
          push: true
          tags: registry.cn-qingdao.aliyuncs.com/wod/beagle-wind-vnc:nvidia-egl-steam-202502131122 # 镜像 tag，根据您的实际情况修改
